### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by crowz4k** [mattzeunert/FromJS#113]
Error: \\?\C:\Users\QPC\AppData\Roaming\npm\node_modules\@fromjs\cli\node_modules\leveldown\build\Release\leveldown.node is not a valid Win32 application.
\\?\C:\Users\QPC\AppData\Roaming\npm\node_modules\@fromjs\cli\node_modules\leveldown\build\Release\leveldown.node
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at bindings (C:\Users\QPC\AppData\Roaming\npm\node_modules\@fromjs\cli\node_modules\bindings\bindings.js:84:48)
    at Object.<anonymous> (C:\Users\QPC\AppData\Roaming\npm\node_modules\@fromjs\cli\node_modules\leveldown\leveldown.js:3:36)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)

**Comment by mattzeunert** [comment]
Seems like [leveldown](https://github.com/Level/leveldown) only supports 64 bit system.

I might look into adding support for storing the result data in memory. That'll be faster too, but will require a few GB of memory.

**Comment by crowz4k** [comment]
I am using windows 10 is there any other way to run?
